### ISSUE TITLE
project workflow 

### ISSUE THREAD

**Issue by sdefreese** [learn-co-curriculum/phase-0-git-basics-lab#3]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4327/assignments/121089?module_item_id=251525

## What should be changed?

Add check boxes or some sort of line by line steps as it was difficult to resume this project when interrupted

**Comment by lizbur10** [comment]
Hi there! Thanks for submitting the suggestion! 

Apologies for the frustrations you encountered. Unfortunately, however, we do not have the capability to add checkboxes to lessons on Canvas at this time. I'm going to go ahead and close this issue, but we will keep your suggestion in mind for the future.

Thanks for providing feedback and contributing to the Flatiron School curriculum. 💙
