### ISSUE TITLE
Error In Lab

### ISSUE THREAD

**Issue by dayjyun** [learn-co-curriculum/phase-0-git-basics-lab#6]
I was completing my-repository-example lab and may have accidentally used phase-0-git-basics-lab's SSH URL by mistake when copying to the syntax. Is there a way that I can check and correct the issue?

**Comment by lizbur10** [comment]
Hi @dayjyun ! Sorry to hear you ran into trouble with this! 

Posting an issue on GitHub is not the best way to get help with this type of problem. GitHub issues are more for reporting an issue with the lab or lesson itself, such as an error in the instructions or the code.

To get help with this, I suggest that you post the question in the #js-prework-support channel in Slack. There are instructors who monitor that channel and who can help you get this straightened out.

I'm going to go ahead and close this issue. 💙
